services:
  metabase: 
    image: metabase/metabase:v0.52.6 
    container_name: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ../database/movies.db:/sqlite-databases/movies.db
      - metabase-data-volume:/metabase-data
volumes:
  metabase-data-volume:
